### ISSUE TITLE
Refactor and test get_migration and get_pop endpoints

### ISSUE THREAD

**Issue by GISRedeDev** [OxfordDemSci/UkraineNowPop#19]

**Comment by GISRedeDev** [comment]
- [x] Check 80+ age group
- [x] Check validation for lower levels
- [x] Add migration count
- [x] Add threshold with limit (20) parameter
- [x] Add count or proportion parameter
- [x] Refactor migration endpoint
- [x] Add get_countries with extents/centroid endpoint

**Comment by GISRedeDev** [comment]
Pull request created [here ](https://github.com/OxfordDemSci/UkraineNowPop/pull/21)

**Comment by GISRedeDev** [comment]
Hi @alaparicioc . Thank you for merging [issue 19](https://github.com/OxfordDemSci/UkraineNowPop/tree/gisrede_issue19_migration_with_threshold). I'll go ahead and delete this this evening if you're happy.

**Comment by edarin** [comment]
Eya! I am trying to install the API and the UI on my computer and I run on the postgis extension issue:
![image](https://github.com/OxfordDemSci/UkraineNowPop/assets/20658648/38ff89f5-dc66-465d-8ae3-4b4083d967af)

Any idea? @GISRedeDev
