### ISSUE TITLE
API unit tests

### ISSUE THREAD

**Issue by GISRedeDev** [OxfordDemSci/UkraineNowPop#22]

**Comment by GISRedeDev** [comment]
- [x] Make test tables subset
- [ ] conftest
- [ ] test database
- [ ] test endpoints
- [ ] test queries
- [ ] test utils
- [ ] test authentication, limiter and security

**Comment by doug-leasure** [comment]
@GISRedeDev , have you completed these unit tests? If so, let's close this issue.
