### ISSUE TITLE
Get controlled territories

### ISSUE THREAD

**Issue by edarin** [OxfordDemSci/UkraineNowPop#24]
We want to have a daily vector layer of the areas controlled by the Russian army.

I have worked on extracting the data displayed by [https://www.deepstatemap.live/#8/47.031/33.179](https://www.deepstatemap.live) with their underlying api: https://deepstatemap.live/api/history/.
I got inspiration from: [https://github.com/conflict-investigations/deepstatemap-territory](https://github.com/conflict-investigations/deepstatemap-territory).

I filtered occupied territories with this re pattern: `'уп|ОРДЛО|Крим'`.
The first one can be read as `up` and allows to by pass issue in encoding the cyrillic `k`. The second one is referred to as the ODLO provinces that is the separatist areas of Luhansk and Donetsk. The last one is Crimea.

When running the `deepstate.py` script stored under `/covariates`, it creates the output in the data folder under `/control`.

**Comment by edarin** [comment]
@GISRedeDev you might want to check out this script: https://github.com/OxfordDemSci/UkraineNowPop/blob/24-get-controlled-territories/src/covariates/deepstate.py

**Comment by GISRedeDev** [comment]
@edarin Thanks a lot for this. I will take a look this week.
