### ISSUE TITLE
Dashboard skeleton codebase

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#4]
Add the codebase for the skeleton of the dashboard. This will help us know where to start working on database schema, etc.

**Comment by GISRedeDev** [comment]
[Pushed to issue-4-dashboard-skeleton-codebase](https://github.com/OxfordDemSci/UkraineNowPop/pull/8)

**Comment by doug-leasure** [comment]
Resolved with PR #4
