### ISSUE TITLE
base model

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#43]
@alaparicioc , if not already available in this repository, could you please add working code for the base model that produces daily population estimates from Facebook and Instagram data? I am looking for the base model that does not include a mobility matrix. I just want to be sure that we have the base model working and producing similar results to our previous estimates that used the same data. 

I will create a branch linked to this issue for you to do this work, and then please submit a pull request and tag me as the reviewer when you are ready. Thanks!  

Note:  I produced a working Stan model using simulated data for Gaza that may be useful for you. 
https://github.com/OxfordDemSci/GazaNowPop/blob/13-bayesian-population-estimates/src/simulation/models/modelB.stan

Please compare your results to our previous population estimates that were produced from the same data using a deterministic approach. Those estimates are publicly available here: https://osf.io/z2jbc/

**Comment by doug-leasure** [comment]
Model options:
1. Gaza-style penetration ratio model that disaggregates total national pop using Dirichlet
2. N-mixture model, maybe with a Dail-Madsen open population model
3. Population change rate for process model + Gaza-style penetration ratio

**Comment by alaparicioc** [comment]
1. JAGS Gaza-style model that disaggregates total national pop by Oblast only using Dirichlet is: https://github.com/OxfordDemSci/UkraineNowPop/blob/95c829050e311b3e9fe63df6ca7cbd3ba8d51261/src/2_model/models/jags_Gaza_style_model.p2 

The results are in: "~home\DemSci\projects\2023_WHO_Ukraine_Population\tmp\SRF_Data analysis\results\oct\results_20241001"

Results include comparison with Leasure et. a.l. (2022). Current estimates resulted with smaller populations mostly in the East than Leasure et. a.l. (2022), and bigger population estimates mostly in the North, West and South than Leasure et. a.l. (2022).

**Comment by alaparicioc** [comment]
1. Stan Gaza-style model that disggregates total national pop by Oblast only using Dirichlet is here: https://github.com/OxfordDemSci/UkraineNowPop/blob/3d839b5d47495a0bd9433d5e961e0f08464c8711/src/2_model/models/stan_Gaza_style_model.stan

**Comment by alaparicioc** [comment]
2. JAGS "N-mixture" model with repeated measuarements: https://github.com/OxfordDemSci/UkraineNowPop/blob/2529df74aa183e46ae42b70156e116882d3bd34f/src/2_model/models/jags_model_multiple_meas.p2

**Comment by alaparicioc** [comment]
3. JAGS model with population change rate for process model: https://github.com/OxfordDemSci/UkraineNowPop/blob/4bf966fb014c9287238dc8a0ad1d1f98da8c6a61/src/2_model/models/jags_model_growth_rate.p2

**Comment by alaparicioc** [comment]
Next step: Reparametrisation of model to include random effects to borrow information among regions.

**Comment by alaparicioc** [comment]
2. JAGS "N-mixture" model with repeated measuarements, allowing borrowing information among Oblasts: https://github.com/OxfordDemSci/UkraineNowPop/blob/73806017a24872a8180172e4131481a32c146b1c/src/2_model/models/2.%20jags_model_multiple_meas_re.p2

**Comment by doug-leasure** [comment]
Thanks @alaparicioc! How are these models fitting? Do you have some indication of their performance?

Can you point me to the code that you are using to actually run these models? I would like to run them myself, but I only see the script for post-processing. Sorry if I've missed it somewhere. 

I'm curious:  What are the estimates of `nuF`, `nuG`, and total population for the country (e.g. for the last time step that you are modelling)?

**Comment by alaparicioc** [comment]
you mean the R code to run the jags models?
There are some weird patterns such us 
![comparison_Center_and_city1](https://github.com/user-attachments/assets/e44bfc16-fc18-4ba4-a309-691e1eea086f)

**Comment by doug-leasure** [comment]
Yes, the R code to run the models. 

What is DL_estimate_23?

**Comment by alaparicioc** [comment]
DL estimates are the estimates from your initial deterministic method.
Oh, ok. I will include it soon. I am responding from my phone

**Comment by doug-leasure** [comment]
Note: We have a longer time series of estimates from the deterministic model in our DemSci project folder that were generated after that paper was submitted.

**Comment by alaparicioc** [comment]
yes, you were right, I was taking the old estimates.
![image](https://github.com/user-attachments/assets/996a2263-d4d0-4ba2-8f18-0b46ef868513)
