### ISSUE TITLE
mobility matrix

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#44]
@alaparicioc , could you please add the model code for your working model that includes the mobility matrix? This used the log-linear modelling framework with a Multinomial model to estimate the mobility matrix from the margins estimated using the Facebook/Instagram observation models.

This is a model that you already had working but that was not committed to GitHub. We need it here so we don't accidentally lose it. 

You can do this work in the same branch as issue #43 , which I have also linked to this issue.

**Comment by doug-leasure** [comment]
@alaparicioc , have you committed this code so that we have it for future referenc?

**Comment by doug-leasure** [comment]
This issue was not resolved by PR #57 . 

@alaparicioc , could you please indicate if you intend to commit the code for your log-linear model, or should we close this issue without resolution?

**Comment by alaparicioc** [comment]
Hi. Apologies for this. The model is on: "https://github.com/OxfordDemSci/UkraineNowPop/blob/923041ddd2d60ef498e871b9e801d6e8e710a1c3/src/2_model/models/migration-matrix-old/migration-matrix-old.p2"

**Comment by doug-leasure** [comment]
Thanks!
