### ISSUE TITLE
Prepare Facebook and Instagram data for N-mixture model

### ISSUE THREAD

**Issue by edarin** [OxfordDemSci/UkraineNowPop#51]
Create a multi dimensionnal array from social media audience count [T, I, M]

## Example: 
number of time steps T = 5
number of locations I = 10
number of repeat observations M = 3

, , 1

      [,1]  [,2]  [,3]   [,4]  [,5]  [,6]   [,7]  [,8]   [,9] [,10]
[1,] 62257 70629 74247 100837 81966 93603 105083 17240 121485 52538
[2,] 77470 78820 83454  92405 61111 74169  73979 45906 126350 59726
[3,] 84242 61790 54329  92245 74535 71446  99370 47028  81050 69238
[4,] 88176 73082 71399  83766 53805 97446  90900 60763  97364 71998
[5,] 84943 77365 55618  84110 79864 90989  69397 65343  65044 64981

, , 2

      [,1]  [,2]  [,3]   [,4]  [,5]  [,6]   [,7]  [,8]   [,9] [,10]
[1,] 62406 70412 74890 100407 82269 94043 104727 17149 121244 52325
[2,] 77620 78730 83535  91723 61379 73824  74225 45676 126977 59809
[3,] 84383 61937 54782  91682 75283 71370  99544 47452  81149 69804
[4,] 87797 72878 71378  84389 53907 97765  90581 60614  97123 72369
[5,] 85192 77335 55987  84504 80060 90796  69364 64874  64825 64700

, , 3

      [,1]  [,2]  [,3]   [,4]  [,5]  [,6]   [,7]  [,8]   [,9] [,10]
[1,] 61999 71133 74707 100627 82258 94352 105199 17227 120853 52525
[2,] 77639 78636 83364  92001 60750 73558  73795 45441 126465 59444
[3,] 84069 62073 54507  91689 74809 71424  99689 47118  80922 69729
[4,] 88001 73237 71354  83675 54369 96956  90958 60553  97468 72127
[5,] 84298 77678 55539  83953 80381 90756  69792 65237  64588 64673

**Comment by edarin** [comment]
There are two scripts to address the issue, both stored in `src/1_pop_data`:

1. [10_daily_audience.py](https://github.com/OxfordDemSci/UkraineNowPop/blob/51-prepare-facebook-and-instagram-data-for-n-mixture-model/src/1_pop_data/10_daily_audience.py)
it is now set to query one year of Facebook and Instagram data for the `T_13Plus`. Output is stored in `2023_WHO_Ukraine_Population\\output\\population_proxy\\social_media_audience\ua_[platform]_audience.csv`.

2. [11_process_daily_audience.R](https://github.com/OxfordDemSci/UkraineNowPop/blob/51-prepare-facebook-and-instagram-data-for-n-mixture-model/src/1_pop_data/11_process_daily_audience.R)
It has a function to convert the audience into a 3d array [week, oblast, day_of_week]. 
The output for the models are stored in `2023_WHO_Ukraine_Population\\output\\population_proxy\\model_data\[platform]_md.rds`.
It creates also a dataframe summarising missing observations per oblast, week and day of the week.
![image](https://github.com/user-attachments/assets/2a24e22e-4a3c-4815-8244-f14d81bc9711). 
I would advise to remove at least weeks that have less than one observation per oblast (`n_obs`).
It is stored in `2023_WHO_Ukraine_Population\\output\\population_proxy\\model_data\[platform]_md_missing.rds`

**Comment by doug-leasure** [comment]
PR #52 mostly resolved this issue, but we realised a couple of other things that need to be done: 

- [x] Ensure that all locations with data within our date range are included in the `md` object, even if they don't have data for many dates
- [x] Include Facebook data `md$y_F` and Instagram data `md$y_G` in the same `md` object. 
- [x] Add a vector `md$locations_F` that includes a numeric identifier (e.g. meta_key or pcode) for each location in the array `md$y_F`
- [x] Add a vector `md$locations_G` that includes a numeric identifier (e.g. meta_key or pcode) for each location in the array `md$y_G`

Note: The location identifiers cannot contain any text characters or Stan will raise an error.

**Comment by doug-leasure** [comment]
@edarin , just for a bit more context:  I will add baseline population data into `md$N0` which needs to be a vector of length `I` that has the baseline population for each location. I will pull that data from `.../input/COD-PS/ukr_admpop_adm1_2022.csv` and I need to be able to match those baseline pop data with the correct locations in the FB and IG data. 

This bit will happen in the model prep script, so that I have flexbility to modify age-groupings, etc for different models.

**Comment by edarin** [comment]
Is that correct that you would need also: `md$M_F` and `md$M_G`. As well as `T_F` and `T_G` as they might not be the same across collections

**Comment by edarin** [comment]
You may have noticed but we collected `T_20Plus` only starting on the 6th Nov 2022 when `T_13Plus` starts on the 27th Feb 2022. So we may want to revert to 13Plus...

**Comment by doug-leasure** [comment]
> Is that correct that you would need also: `md$M_F` and `md$M_G`

Yep, that's correct. 

> You may have noticed but we collected T_20Plus only starting on the 6th Nov 2022 when T_13Plus starts on the 27th Feb 2022. So we may want to revert to 13Plus...

Oh, I hadn't noticed that. Okay, yeah. probably should stick with 13Plus for now.

**Comment by alaparicioc** [comment]
for the indexing and respective labels, the following can be useful:

pcode = factor(pcode, levels = c("UA01", "UA05", "UA07", "UA12", "UA14",
                                            "UA18", "UA21", "UA23", "UA26", "UA32",
                                            "UA35", "UA44", "UA46", "UA48", "UA51",
                                            "UA53", "UA56", "UA59", "UA61", "UA63",
                                            "UA65", "UA68", "UA71", "UA73", "UA74",
                                            "UA80", "UA85")),
         
         geo_name = case_when(pcode=="UA01" ~ "Autonomous Republic of Crimea",
                              pcode=="UA71" ~ "Cherkasy Oblast",
                              pcode=="UA74" ~ "Chernihiv Oblast" ,
                              pcode=="UA73" ~ "Chernivtsi Oblast",
                              pcode=="UA12" ~ "Dnipropetrovsk Oblast",
                              pcode=="UA14" ~ "Donetsk Oblast",
                              pcode=="UA26" ~ "Ivano-Frankivsk Oblast",
                              pcode=="UA63" ~ "Kharkiv Oblast",
                              pcode=="UA65" ~ "Kherson Oblast",
                              pcode=="UA68" ~ "Khmelnytskyi",
                              pcode=="UA35" ~ "Kirovohrad Oblast",
                              pcode=="UA80" ~ "Kyiv",
                              pcode=="UA32" ~ "Kiev Oblast",
                              pcode=="UA44" ~ "Luhansk Oblast",
                              pcode=="UA46" ~ "Lviv Oblast",
                              pcode=="UA48" ~ "Mykolaiv Oblast",
                              pcode=="UA51" ~ "Odessa Oblast",
                              pcode=="UA53" ~ "Poltava Oblast",
                              pcode=="UA56" ~ "Rivne Oblast",
                              pcode=="UA85" ~ "Sevastopol",
                              pcode=="UA59" ~ "Sumy Oblast",
                              pcode=="UA61" ~ "Ternopil Oblast",
                              pcode=="UA05" ~ "Vinnytsia Oblast",
                              pcode=="UA07" ~ "Volyn Oblast",
                              pcode=="UA21" ~ "Zakarpattia Oblast",
                              pcode=="UA23" ~ "Zaporizhia Oblast",
                              pcode=="UA18" ~ "Zhytomyr Oblast"), 
         
         macroregion = case_when(
           geo_name=="Autonomous Republic of Crimea"~"Autonomous",
           geo_name=="Cherkasy Oblast"~"Center",
           geo_name=="Chernihiv Oblast"~"North",
           geo_name=="Chernivtsi Oblast"~"West",
           geo_name=="Dnipropetrovsk Oblast"~"East",
           geo_name=="Donetsk Oblast"~"East",
           geo_name=="Ivano-Frankivsk Oblast"~"West",
           geo_name=="Kharkiv Oblast"~"East",
           geo_name=="Kherson Oblast"~"South",
           geo_name=="Khmelnytskyi"~"West",
           geo_name=="Kiev Oblast"~"North",
           geo_name=="Kirovohrad Oblast"~"Center",
           geo_name=="Kyiv"~"City",
           geo_name=="Luhansk Oblast"~"East",
           geo_name=="Lviv Oblast"~"West",
           geo_name=="Mykolaiv Oblast"~"South",
           geo_name=="Odessa Oblast"~"South",
           geo_name=="Poltava Oblast"~"Center",
           geo_name=="Rivne Oblast"~"West",
           geo_name=="Sevastopol"~"Autonomous",
           geo_name=="Sumy Oblast"~"North",
           geo_name=="Ternopil Oblast"~"West",
           geo_name=="Vinnytsia Oblast"~"Center",
           geo_name=="Volyn Oblast"~"West",
           geo_name=="Zakarpattia Oblast"~"West",
           geo_name=="Zaporizhia Oblast"~"East",
           geo_name=="Zhytomyr Oblast"~"North"),

age_group10y = factor(age_group10y, levels = c("0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-999")

**Comment by doug-leasure** [comment]
Closed with PR #53
