### ISSUE TITLE
crossing borders - R code

### ISSUE THREAD

**Issue by alaparicioc** [OxfordDemSci/UkraineNowPop#54]
This code corresponds how I am retrieving data on border crossings weekly and daily, as well as the interpolation I mentioned. The code is located in 
https://github.com/OxfordDemSci/UkraineNowPop/blob/fa4d7eba5cff387921e00d4fa70129dca010163f/data/border%20crossings/border_crossings.R

**Comment by edarin** [comment]
Cool!
The data folder though as written in the [readme](https://github.com/OxfordDemSci/UkraineNowPop/tree/fa4d7eba5cff387921e00d4fa70129dca010163f/data) is only for data files, not for scripts.
I think the best folder would be: src/1_pop_data.
To see it it should be on the dev branch.

**Comment by alaparicioc** [comment]
i pasted the wrong link, sorry
