### ISSUE TITLE
prototype covariates

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#56]
Create a few prototype covariates (X) of population growth rates (R):
```
N[t,i] = N[t-1,i] * R[t,i]
R[t,i] ~ lognormal(mu_R[t,i], sigma_R)
mu_R[t,i] = alpha + X[t,i] * beta
```
Here i = oblast and t = calendar week (starting Mondays)

A few ideas to start with:
- [x] ACLED conflict events by type (e.g. explosions, battles, violence against civilians, strategic developments)
- [x] Building damage compared to pre-invasion baseline (called PWTT as per Ollie's algorithm)
- [x] Air raid sirens
- [x] War fires
- [x] Areas of control (Ukraine, Russia)

Let's explore a few types of scaling for covariates:
- Scaled globally (i.e. `(x - mean(x)) / sd(x)`)
- Scaled using weekly mean and sd calculated across all locations
- Scaled using location-specific mean and sd calculated across all time steps prior to the current date

----

As a _second_ priority, we also need a few covariates for detection rates `p_F` and `p_G` that will be modeled something like this: 
```
F[t,i] ~ poisson(N[t,i] * p_F[t,i])
logit(p_F[t,i]) = alpha[i] + X[t,i] * beta

G[t,i] ~ poisson(N[t,i] * p_G[t,i])
logit(p_G[t,i]) = alpha[t] + X[t,i] * beta
```

A couple of ideas for potential data sources: 
- [ ] [Netblocks ](https://netblocks.org/ukraine-crisis) network connectivity
- [ ] Any direct measure of electricity outages?
- [ ] Nighttime lights intensity relative to expected baseline intensity as a proxy for electricity outages

**Comment by alaparicioc** [comment]
@edith, could you check which indicators may be useful from https://www.ukrstat.gov.ua/. We may be able to get time series and by oblast from the selected ones, but we need to define which ones would be useful for our purposes.

**Comment by edarin** [comment]
> Let's explore a few types of scaling for covariates:
> 
>     Scaled globally (i.e. (x - mean(x)) / sd(x))
>     Scaled using weekly mean and sd calculated across all locations
>     Scaled using location-specific mean and sd calculated across all time steps prior to the current date
I would add a cumulated sum (to distinguish the fatigue from conflict events). 
Regarding the time-specific scaling I would have say maybe within a time window prior to the current date. 3 months maybe?

>  could you check which indicators may be useful from https://www.ukrstat.gov.ua/. We may be able to get time series and by oblast from the selected ones, but we need to define which ones would be useful for our purposes.

I briefly had a look at the indicators. It is interesting. However we would need something that vary subnationally and subyearly I think for informating the growth rate especially when we lost the population signals. These levels of resolution dont seem to be available. 
Let's keep in mind this data source to estimate flows however as it could inform the modelling of the baseline of flows due to push/pull factors.

**Comment by doug-leasure** [comment]
@edarin It would be helpful to create a couple of covariates on detection rates as well. The base model (see #67) struggles to estimate detection for Luhansk, Donetsk, Crimea, and Sevastopol because there was as sharp decline in those oblasts due to network and electricity outages as well as intentional blocking of Facebook and Instagram. Perhaps, [NetBlocks ](https://netblocks.org/ukraine-crisis)and/or nighttime lights would be good places to start?

I edited the issue description to include these.

**Comment by alaparicioc** [comment]
Could two variables related to macroregion be created? The first one would be something like:
```
macroregion = case_when(
           geo_name=="Autonomous Republic of Crimea"~"Autonomous",
           geo_name=="Cherkasy Oblast"~"Center",
           geo_name=="Chernihiv Oblast"~"North",
           geo_name=="Chernivtsi Oblast"~"West",
           geo_name=="Dnipropetrovsk Oblast"~"East",
           geo_name=="Donetsk Oblast"~"East",
           geo_name=="Ivano-Frankivsk Oblast"~"West",
           geo_name=="Kharkiv Oblast"~"East",
           geo_name=="Kherson Oblast"~"South",
           geo_name=="Khmelnytska"~"West",
           geo_name=="Kiev Oblast"~"North",
           geo_name=="Kirovohrad Oblast"~"Center",
           geo_name=="Kyiv"~"City",
           geo_name=="Luhansk Oblast"~"East",
           geo_name=="Lviv Oblast"~"West",
           geo_name=="Mykolaiv Oblast"~"South",
           geo_name=="Odessa Oblast"~"South",
           geo_name=="Poltava Oblast"~"Center",
           geo_name=="Rivne Oblast"~"West",
           geo_name=="Sevastopol"~"Autonomous",
           geo_name=="Sumy Oblast"~"North",
           geo_name=="Ternopil Oblast"~"West",
           geo_name=="Vinnytsia Oblast"~"Center",
           geo_name=="Volyn Oblast"~"West",
           geo_name=="Zakarpattia Oblast"~"West",
           geo_name=="Zaporizhia Oblast"~"East",
           geo_name=="Zhytomyr Oblast"~"North"),
         
         macroregion_id = case_when(
           macroregion=="Autonomous" ~ 1,
           macroregion=="East" ~ 2,
           macroregion=="South" ~ 3,
           macroregion=="Center" ~ 4,
           macroregion=="City" ~ 5,
           macroregion=="North" ~ 6,
           macroregion=="West" ~ 7
```
Notice that in this first one, the macroregion_id has the seven macroregions, but it would be nice to have a second one named e.g. macroregion2_id, in which east and autonomous are grouped. Something like 
```
         macroregion1_id = case_when(
           macroregion=="Autonomous" ~ 1,
           macroregion=="East" ~ 1,
           macroregion=="South" ~ 2,
           macroregion=="Center" ~ 3,
           macroregion=="City" ~ 4,
           macroregion=="North" ~ 5,
           macroregion=="West" ~ 6
```
Feel free to shorten the names.

**Comment by edarin** [comment]
Thanks for providing the code!
I am thinking of calling it `j` and `j_name` because geo_name is now `i`. How does that sound?

You dont have anything for `Khmelnytska`. Which macro-region?

I am not a big fan of creating two indices in the master_index with different overlaps. What do you think of recreating the index from `j_name` as you build up the md and once you are certain about the partitioning i'll take it on (or you add it to the create_master_index script)?

lastly I think @doug-leasure was adamant about having master_index grouping the index of N the latent population parameter. `j` is not an index of N. But I would be in favour of having `j` as part of master_index nevertheless.

**Comment by edarin** [comment]
### On missing observations:
The covariates might have some (i,t) missing either because (1) nothing happened on that week (cf war fire, acled) or (2) the data is only available on a monthly basis (building damages).

I would be in favor of:
for (1) replacing missing by 0 such having a complete set of (i,t) observations
for (2) interpolating using piecewise linear interpolant (`np.interpolate(method='linear')`)

**Comment by alaparicioc** [comment]
Sure j seems reasonable. Be aware that when we adopt the origin-destination matrix, we need another letter for origins.

> Khmelnytskyi

The names in Ukraine has different spelling, i do not know depending on what. I think that Khmelnytskyi=Khmelnytska, which is West.

Yes, i thought initially macroregion as part of the master_index as well. We could discuss it at some point as well as the best point of the pipeline to create this part.

**Comment by alaparicioc** [comment]
> ### On missing observations:
> The covariates might have some (i,t) missing either because (1) nothing happened on that week (cf war fire, acled) or (2) the data is only available on a monthly basis (building damages).
> 
> I would be in favor of: for (1) replacing missing by 0 such having a complete set of (i,t) observations for (2) interpolating using piecewise linear interpolant (`np.interpolate(method='linear')`)

I agree with your solution (1). For (2), I think it would depend on the variable. Interpolating can artificially smooth the data. In the case of building damage which is monthly data, interpolation could suggest a trend of increasing or decreasing damage that does not exist. This also happends with population. Researchers tend to repeat the same value across the desired period. We could discuss this decision at some point.

**Comment by doug-leasure** [comment]
Great to see this conversation! Thanks to you both. 

I might consider formatting macro region groupings as covariates that are just columns in the covariate matrix (rows = oblasts, columns = covariates). This gives flexibility to have various different regions definitions. I don't really see them as part of the master index, but happy to follow your lead here. 

Missing data are fine. We can handle that on the modelling side for now, or as an intermediate step if we want to do some interpolation.

**Comment by edarin** [comment]
Regarding macroregion:
I think it's better to have it in master_index. Indeed it doesnt vary across time and not "a lot" across oblast. And it will use as an index rather than as an X in the model right? I suggest to create a `r_name` (and not `j` you are right Andrea) and then, temporarily, in the md you create an index, `r` based on the custom grouping. How does it sound?

**Comment by edarin** [comment]
Regarding covariates:
Ok no interpolating or filling missing values then! It will be cov_i_t as being observed in the data source. So missing combination of i,t wont be present in the dataset. Agreed?
_(i wrote two comments to separate emojis 😄 )_

**Comment by alaparicioc** [comment]
> Regarding covariates: Ok no interpolating or filling missing values then! It will be cov_i_t as being observed in the data source. So missing combination of i,t wont be present in the dataset. Agreed? _(i wrote two comments to separate emojis 😄 )_

I would prefer to have all combinations of i,t even though they have missing values. in that way, we could assess level of missingness.

**Comment by edarin** [comment]
> I would prefer to have all combinations of i,t even though they have missing values. in that way, we could assess level of missingness.

I agree. Beyond assessing level of missingness any other transformation of the covariates as listed as the beginning of the issue (custom standardisation) would need all the combination.

For occurences type of covariates (acled, sirens, fire) I think a 0 makes sense.
For snapshot covariates (building damages available as a monthly measurement) I would like your guidance. Either leaving as it is with a signal every 4 t. but then any other derivatives cant be computed. Or replicating measurement for 4 ts. Seems not correct as it will mean a sharp increase each 4ts. So I would think basic interpolation. Thoughts?

**Comment by doug-leasure** [comment]
@edarin Does PR #75 close this issue?

**Comment by edarin** [comment]
depends if you integrate (1) scaling (2) network connectivity covariates ;)

**Comment by doug-leasure** [comment]
I think we should probably separate those into their own issues.
