### ISSUE TITLE
standardise model inputs

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#58]
We want to implement a data standard for all of the data going into the model(s) that has the following characteristics:
1. A master index csv that contains indexes for every time step (t), location (i), sex (s), age (a), sampling event (m), etc along with metadata columns to define these indexes (e.g. date, location_name, pcode, meta_key, age-sex definition, etc)
2. A csv for every data node in the model that includes a column for each subscript included for the data node as well as a column for the variable values. For example, the csv for the Facebook audience data `F[t,i,m]` would include columns "t", "i", "m", and "value". The indices used for t, i, and m would match those in the master index csv (above)
3. Because these data and indexing will vary among models, it may be most efficient to write a function or set of functions to generate these data allowing arguments to be modified like age-sex groupings, time step, etc. 

The person developing each model will be responsible for converting this data format into the list object required by stan or jags and making any necessary adjustments to match the requirements of their model.

Our goal for now is just to implement a prototype of this and then we can modify as needed going forward.

**Comment by alaparicioc** [comment]
@edarin, as we were talking, I think your idea of creating the function that retrieves the data based on the age groups that we need for the modelling part is nice instead of working with sub-setting the "full" dataset. I have been working with age groups as follows: 

"age_min >=20, 
         age_max <=64,
         age_max-age_min == 4"

"age_min >=20, 
         age_max <=64,
         age_max-age_min == 9"

Could the functions include age groups which allow e.g. starting at age_min >=18?

**Comment by edarin** [comment]
I am really tempted to create in master_index a column with collection_date or `d` which is daily to match with `t` which is weekly.
I need that for processing all the covariates. Would that be ok on your side?
It will make master_index redundant for N_i_t as it would be N_i_t_d.
I could also create a separate time_index.csv that would give me the t-d matching. WHat do you prefer?

**Comment by doug-leasure** [comment]
> I am really tempted to create in master_index a column with collection_date or `d` which is daily to match with `t` which is weekly. I need that for processing all the covariates. Would that be ok on your side? It will make master_index redundant for N_i_t as it would be N_i_t_d. I could also create a separate time_index.csv that would give me the t-d matching. WHat do you prefer?

Yep, all good to include additional columns in the master_index.csv.

**Comment by edarin** [comment]
I have decided to stick with master_index being N_i_t_a_s. I will add pcode when I'll have access to the file.
I have outputed a time_index.csv that is longer and matches all day dates during the war to the corresponding t.

fyi i have now changed the output_dir for the index to be at the root of the output folder as i need it for several branches of the work.

**Comment by alaparicioc** [comment]
The weekly step that you are including is every Monday, right? I thougth it was going to be Sundays. My question is because the mean of the Instagram and Facebook ratios are calculated in the 1_base_model_config.R. Would not we assume that the trend of Mondays are based on  what happened on the rest of the week?
