### ISSUE TITLE
model audience data prep

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#7]
Write an R script to pull Facebook and Instagram data from the API and format them as inputs for the Stan model. 

These data should be written into a subfolder of the `./wd/` directory which is included in the .gitignore so they will not be committed to GitHub.

**Comment by doug-leasure** [comment]
@edarin and @alaparicioc , how is the progress on this issue? @alaparicioc , is this code able to produce the model inputs for Facebook and Instagram data that you need?

It looks like this work may be completed. If so, please open pull request to merge this branch back in to main so that we can close this issue.

**Comment by alaparicioc** [comment]
We were thinking that we kept this branch open to see if I needed anything else. However, I think I could get what I needed from here.
