### ISSUE TITLE
Add deterministic comparison to pipeline

### ISSUE THREAD

**Issue by alaparicioc** [OxfordDemSci/UkraineNowPop#76]
Hi @edarin,

If this has not been done yet, could you integrate the deterministic comparison code into the current pipeline?

The code I used is here: https://github.com/OxfordDemSci/UkraineNowPop/blob/f666404ca7cbaace5e669f251b9c0b9362482ff0/src/2_model/alt/3_comparison_DL_2023. It will need adjustments to fit the current pipeline.

It could be added after the "2_eval" step.

Thanks.

Andrea

**Comment by doug-leasure** [comment]
@alaparicioc , maybe it would be better for you and I to handle the model evaluation code? This is something that may need to vary depending on the specifics of the model.

**Comment by alaparicioc** [comment]
@doug-leasure , shall I close this issue since this is model-dependent?

**Comment by doug-leasure** [comment]
@alaparicioc If you plan to work on it, then please keep it open and set its status to "in progress" (under Projects). 

If you don't plan to work on it, then let's close it for now.

**Comment by alaparicioc** [comment]
Noted. I will work on it between this and the next week.

**Comment by alaparicioc** [comment]
I have included this issue under progress

**Comment by alaparicioc** [comment]
From I have reviewed of issue #91 , it seems that this issue has been included. So, I will close this.

**Comment by doug-leasure** [comment]
I don't think that PR #91 compares any modeled population estimates with the deterministic estimates. But, I'm still happy to close this issue as I think we really need to focus on out-of-sample cross-validation for model evaluation anyways.

**Comment by edarin** [comment]
It creates a table with the deterministic estimates that can then be pulled for comparison purposes.
