### ISSUE TITLE
Treatment of 0s in Social media data

### ISSUE THREAD

**Issue by alaparicioc** [OxfordDemSci/UkraineNowPop#78]
Hi,

I wanted to raise the matter related to handling 0s in the social media data. I usually treat them as NA to reduce noise. Leaving them in has caused problems in the age-sex model, similar to the issues we had with oblasts in the Autonomous and East regions. @Doug, I’m not sure if you’ve encountered the same in your model attempsts with age and sex.

I’ve been removing the 0s at the equivalent step in Doug’s code here:
https://github.com/OxfordDemSci/UkraineNowPop/blob/f666404ca7cbaace5e669f251b9c0b9362482ff0/src/2_model/models/1_base_model_config.R

However, I’m wondering if we should standardise this approach earlier in the pipeline:
https://github.com/OxfordDemSci/UkraineNowPop/blob/f666404ca7cbaace5e669f251b9c0b9362482ff0/src/1_pop_data/20_prepare_sma_data.R

Best regards,

Andrea Aparicio

**Comment by doug-leasure** [comment]
I drop zeros and NAs [here](https://github.com/OxfordDemSci/UkraineNowPop/blob/f666404ca7cbaace5e669f251b9c0b9362482ff0/src/2_model/models/1_base_model_config.R#L46).

I would prefer to leave this filtering in the model-specific code that creates the model data object `md`. As we move towards more advanced models, we may want to use these zeros and threshold values (e.g. threshold MAU=1000).  These data points do contain some information, but our simple models cannot handle this at the moment. A zero-inflated observation model could handle the zeros, and a more complex observation model could handle the threshold values.
