### ISSUE TITLE
Standardise covariates

### ISSUE THREAD

**Issue by edarin** [OxfordDemSci/UkraineNowPop#80]
We want to standardise covariates across time and location to pick up different forms of signal.
The current methodology is, with $x_{i,t}$ the raw covariate and $X_{i,t}$ the standardised covariate:
- Z-score scaling: 
$X_{i,t} = \frac{x_{i,t} - \bar{x}}{sd(x)}$
- Z-score cumulative scaling: 
$y_{i,t}= \sum_{u=t-t_0}^{t}x_u$
$X_{i,t} = \frac{y_{i,t} - \bar{y}}{sd(y)}$
- Z-score temporal scaling:
$y_{i,t}=  x_{i,t} - mean(x_{i,t}, \dotsc , x_{i,t-t0})= x_{i,t} - \frac{1}{t_0}\sum_{u=t-t_0}^{t}x_{i,u}  $
$X_{i,t} = \frac{y_{i,t}}{sd(y)}$
- Z-score geographical scaling:
$y_{i,t}= x_{i,t} - mean(x_{i,t}, x_{j,t}, \dotsc , x_{l,t}$)
$X_{i,t} = \frac{y_{i,t}}{sd(y)}$

There are three "hyperparameters" :
1. $t_0$ in the cumulative scaling that is the time window for the cumulative effect
2. $t_0$ in the temporal scaling that is the time window for the baseline comparison
3. $j, \dotsc , l$ in the geographical scaling that is the geographical window for the baseline comparison.

Current ideas are:
1. 1 month, 3 months, 6 months
2. 1 month, 3 months, 6 months
3. Maybe a distance weighted mean based on the population weighted centroid? The simplest is to fall back on the macroregion.

The last step is to visualise the correlation between the covariates and the output of interest, with different lag and lead.

**Comment by alaparicioc** [comment]
Hi,

I have some questions related to this:

(1) What do you mean when you are referring to standarisation?
(2) Why are you doing standardising?

You may have already discussed the previous aspects, but I just wanted to know to see if I can contribute to anything here.

**Comment by edarin** [comment]
When talking about standardisation, I refer to processing the covariates such that they can be all compared on the same scale but also such that a different signal can be picked. This process can also be called re-scaling.

As you can see from the equations the two first processing standardise using a z-score that is substracting the mean and dividng by the standard deviation. One use directly the covariate, the second one use the cumulative version of the covariates. They both will have a mean of 0 and a standard deviation of 1.

The last two processing are slightly different. They are meant to pick up relative difference across time and relative difference across geographical space. They wont have however by construction a mean of 0 and a standard deviation of 1. 
Maybe a second step should be added to ensure that?

$y_{i,t}= (x_t, x_{t-1}, \dotsc , x_{t-t_0}$)
$z_{i,t} = \frac{x_{i,t} - \bar{y}}{sd(y)}$
$X_{i,t} =  \frac{z_{i,t} - \bar{z}}{sd(z)}$


$y_{i,t}= (x_i, x_{j}, \dotsc , x_l$)
$z_{i,t} = \frac{x_{i,t} - \bar{y}}{sd(y)}$
$X_{i,t} =  \frac{z_{i,t} - \bar{z}}{sd(z)}$

Is that what you are suggesting?

**Comment by alaparicioc** [comment]
> When talking about standardisation, I refer to processing the covariates such that they can be all compared on the same scale but also such that a different signal can be picked. This process can also be called re-scaling.
> 
> As you can see from the equations the two first processing standardise using a z-score that is substracting the mean and dividng by the standard deviation. One use directly the covariate, the second one use the cumulative version of the covariates. They both will have a mean of 0 and a standard deviation of 1.
> 
> The last two processing are slightly different. They are meant to pick up relative difference across time and relative difference across geographical space. They wont have however by construction a mean of 0 and a standard deviation of 1. Maybe a second step should be added to ensure that?
> 
> y i , t = ( x t , x t − 1 , … , x t − t 0 ) z i , t = x i , t − y ¯ s d ( y ) X i , t = z i , t − z ¯ s d ( z )
> 
> y i , t = ( x i , x j , … , x l ) z i , t = x i , t − y ¯ s d ( y ) X i , t = z i , t − z ¯ s d ( z )
> 
> Is that what you are suggesting?

Thanks for the clarifications! I was thinking more about standardisation as in your first equation. I am not entirely sure we need to standardise the geographical and temporal scaling, although, theoretically, doing so would improve comparability among predictors. My initial thought was about how to validate whether the temporal and geographical signals are being captured effectively, ensuring that our estimates of true populations are improving rather than worsening (i.e., avoiding results that are overly influenced by the chosen scaling methods or parameters).

You mentioned different time windows (1, 3, and 6 months). Are these based on specific data characteristics or just expected temporal dynamics? Does the data support all of these time windows effectively?

For geographical scaling, I agree that using macroregions would be simpler for the distance-weighted mean. However, relying on centroids in large geographical units often affects estimates, as seen in gravity models. Would it be possible to start with oblasts instead? From the equation, it seems you could plug in oblast-level values directly, could not you?

**Comment by edarin** [comment]
>Thanks for the clarifications! I was thinking more about standardisation as in your first equation. I am not entirely sure we need to standardise the geographical and temporal scaling, although, theoretically, doing so would improve comparability among predictors.

I see your point. I am thinking now that it might be good to add a standardisation step on top of the scaling step. Thanks for pointing it out!

> You mentioned different time windows (1, 3, and 6 months). Are these based on specific data characteristics or just expected temporal dynamics? 

These windwos were more related to expected temporal dynamics and interpretation power. ie constant war fires during the last three months has a different expected effect than one fire during the week. Would you have other time windows in mind? The idea is not to have too many variations but solid argumentation for each.

> Does the data support all of these time windows effectively?

This is a valid question. For the building damage covariate 1 month window wont provide that much more information. So maybe only 3 and 6 for pwtt but 1, 3, 6 for the rest of the covariates? (All the other covariates are daily without any imputation, interpolation etc)

> For geographical scaling, I agree that using macroregions would be simpler for the distance-weighted mean. However, relying on centroids in large geographical units often affects estimates, as seen in gravity models. Would it be possible to start with oblasts instead? From the equation, it seems you could plug in oblast-level values directly, could not you?

This question is not clear to me. All the covariates will be computed for the oblast as this is the unit of analysis currently. The aim is to define a metric to compare the x for one oblast to the x of the surrounding oblasts. If we use macroregion then we are artificially defining neighbouring oblast as one oblast on the edge of a macroregion is closer to oblasts in another macroregion than its own macroregion. So I am a bit hesitant to adopt this strategy. The second strategy could be to define the reference as the mean of all the oblasts that share a border with the oblast in scope. But the third strategy which is the most complicated but as well the most exciting one as always is to define as the reference the weighted mean of the xs from all other oblast, with the weights being the inverse of the distance between the centroids of the oblast. And the ultimate trick will be to define the centroid of an oblast not as the geographical centroid but as a population weighted centroid that is setting the centroid where most of the population of the oblast lives.
Does it make sense?
