### ISSUE TITLE
Fill missing covariates

### ISSUE THREAD

**Issue by edarin** [OxfordDemSci/UkraineNowPop#81]
We want to fill the missing values of covariates due to lack of observations. 
This applies currently only to the building damage data from the PWTT algorithm that can create only one data point per month.
How do we want to fill the weekly values?

**Comment by doug-leasure** [comment]
The simplest option (and hence probably the first to try) would be to fill NAs with the most recent data preceding the NA date that is available for a location. 
Another option would be linear interpolation.
Third option would be model-based imputation, which seems like the best option to me... but also the hardest.

**Comment by edarin** [comment]
This is an example:
![Image](https://github.com/user-attachments/assets/2b72b943-fbd0-4f68-870a-690ab77da701)


I feel that a linear interpolation wont be too bad?

**Comment by alaparicioc** [comment]
For the building damage variable, I lean on filling NAs with the most recent data preceding the NA date that is available for a location.
I have two questions here:
(1) Are the monthly data points the same day? e.g. Every first of each month
(2) Is there any aspect of e.g. the data collection that is causing the missingness? @Doug was mentioning that in some clouded days, the images may not be available.

Apologies if you have discussed the previous aspects before. I want to understand just in case I can contribute to anything here.

**Comment by edarin** [comment]
There are three components to take into account for dating a data point here:
1. Sentinel 2 which is the satellite that produces the images we are working with has a return window of 10 days.
1. Satellite imagery derived product are composite data that is they span over several time points in case of cloud cover.
2. The PWTT algorithm that Ollie developed for detecting building damage (but more realistically building change) is based on comparing an average over a year before the war started (that is '2021-02-22' - '2022-02-22') with two months after the date you request (eg '2022-03-22' - '2022-05-22').
I have requested data for every month on the 22 since the start of the war.

**Comment by alaparicioc** [comment]
> to fill the missing values of covariates due to lack of observations.
> This applies currently only to the building damage data from the PWTT algorithm that can create only one data point per month.
> How do we want to fill the weekly values?

Thanks for the clarifications! Based on your knowledge about the PWTT algorithm, I wonder if we should assume that the one data point per month applies uniformly across all weeks within each calendar month or we should only apply it from the 22nd of the month onward or taking the value for the four nearest weeks (two weeks before the 22nd and two weeks after the 22nd)?

At some point (not now and just as an idea), for weeks with filled values (rather than actual observations), we could "flag" these entries to indicate they are imputed, and could quantify uncertainty around them within the model.

**Comment by edarin** [comment]
I think that if we want to go down the path of replicating the observed values I would probably advise to replicate for the four next week before the next data point, ie if the '2022-05-22' falls on t=5 and '2022-06-22' on t=9, having the value of t=5 for t=5,6,7,8.

I also realised that the default value is one month post actually and not two months so I will need to revisit this window.

**Comment by alaparicioc** [comment]
> I think that if we want to go down the path of replicating the observed values I would probably advise to replicate for the four next week before the next data point, ie if the '2022-05-22' falls on t=5 and '2022-06-22' on t=9, having the value of t=5 for t=5,6,7,8.
> 
> I also realised that the default value is one month post actually and not two months so I will need to revisit this window.

Brilliant! After exploring the suitability of the time window, we can revisit this?

**Comment by edarin** [comment]
This is how it looks like:
![image](https://github.com/user-attachments/assets/8ea0acab-f7be-443b-80b6-578600da860c)

(note tht I have also revisited the way to compute the pwtt itself by looking only at one month forward, default of the algorithm, when previoulsy I was averaging over two months forward)

**Comment by alaparicioc** [comment]
> This is how it looks like: ![image](https://private-user-images.githubusercontent.com/20658648/389023163-8ea0acab-f7be-443b-80b6-578600da860c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjU1MDksIm5iZiI6MTczMjUyNTIwOSwicGF0aCI6Ii8yMDY1ODY0OC8zODkwMjMxNjMtOGVhMGFjYWItZjdiZS00NDNiLTgwYjYtNTc4NjAwZGE4NjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZTQ0NTE1OGMzMDRhOGIyYWViZDIyZDFhMmE2NmRhOTIxMmEzNGIxMzYxOWI2MzU0OTYxMmUzNTE0ZDE1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aMXwPuJLeBHn0q-Cyk-avU-gXQKzht-WMlnyKJ6NSio)
> 
> (note tht I have also revisited the way to compute the pwtt itself by looking only at one month forward, default of the algorithm, when previoulsy I was averaging over two months forward)

This is great! Have you checked how this correlated with the observed data?

**Comment by edarin** [comment]
Ah cheers!
I have been working on different scaling of the covariates (see PR #83 ). I need to revist them a bit and then I will be working of a report type of output that would look at the correlation between all the covariates and the observed data.
