### ISSUE TITLE
Authentication and login endpoint

### ISSUE THREAD

**Issue by GISRedeDev** [OxfordDemSci/UkraineNowPop#9]
- [x] Users table
- [x] Alembic migration
- [x] Endpoint
- [x] validation
- [x] JWT token response
- [x] test
- [x] test in frontend

**Comment by doug-leasure** [comment]
@GISRedeDev , could you please open a pull request to merge these changes back into main? Then we can close this issue as completed.

**Comment by GISRedeDev** [comment]
@doug-leasure Sorry Doug just seen this. I've got a couple of loose ends on that branch which I hope to resolve this weekend. Then I'll request to merge everything with some explanations of what's changed
